src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $text_rec = null;

    
    
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sujet = null;

  

    

    #[ORM\Column(nullable: true)]
    private ?int $id_user = null;

    #[ORM\ManyToOne(inversedBy: 'typeRec')]
    private ?TypeReclamation $typeReclamation = null;

    

   

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTextRec(): ?string
    {
        return $this->text_rec;
    }

    public function setTextRec(?string $text_rec): self
    {
        $this->text_rec = $text_rec;

        return $this;
    }
    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(?string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    

    

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(?int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    /**
     * @return Collection<int, TypeReclamation>
     */
    public function getTypeReclamations(): Collection
    {
        return $this->typeReclamations;
    }

    public function addTypeReclamation(TypeReclamation $typeReclamation): self
    {
        if (!$this->typeReclamations->contains($typeReclamation)) {
            $this->typeReclamations->add($typeReclamation);
            $typeReclamation->setType_r($this);
        }

        return $this;
    }

    public function removeTypeReclamation(TypeReclamation $typeReclamation): self
    {
        if ($this->typeReclamations->removeElement($typeReclamation)) {
            // set the owning side to null (unless already changed)
            if ($typeReclamation->getType_r() === $this) {
                $typeReclamation->setType_r(null);
            }
        }

        return $this;
    }

    public function getTypeReclamation(): ?TypeReclamation
    {
        return $this->typeReclamation;
    }

    public function setTypeReclamation(?TypeReclamation $typeReclamation): self
    {
        $this->typeReclamation = $typeReclamation;

        return $this;
    }

    
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use App\Entity\TypeReclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('text_rec', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('sujet', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('id_user', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            
            ->add('typeReclamation', EntityType::class, [
                'class' => TypeReclamation::class,
                'choice_label' => 'type_r',
                'attr' => ['class' => 'form-control'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Entity\TypeReclamation;
use App\Form\TypeReclamationType;

use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use App\Repository\TypeReclamationRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

class ReclamationController extends AbstractController
{
    #[Route('/reclamation', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $ReclamationRepository , TypeReclamationRepository $TypeReclamationRepository, Request $request): Response
    {
        $searchTerm = $request->query->get('q');
        $typeRec = $request->query->get('type_r');
        if ($searchTerm) {
            $reclamations = $ReclamationRepository->findBySearchTerm($searchTerm);
        } else if ($typeRec) {
            $typeReclamation = $TypeReclamationRepository->findOneBy(['type_r' => $typeRec]);
            $reclamations = $ReclamationRepository->findBy(['typeReclamation' => $typeReclamation], ['text_rec' => 'ASC']);
        } else {
            $reclamations = $ReclamationRepository->findBy([], ['text_rec' => 'ASC']);
        }
        $typeReclamations = $TypeReclamationRepository->findAll();
        return $this->render('reclamation/index.html.twig', [
            'controller_name' => 'ReclamationController',
            'reclamation' => $reclamations,
            'title' => 'Historique',
            'subtitle' => 'reclamation',
            'searchTerm' => $searchTerm,
            'typeReclamations' => $typeReclamations,
            'selectedType' => $typeRec
        ]);
    }

    #[Route('/reclamation/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function add(Request $request, MailerInterface $mailer): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
        $em->persist($reclamation);
        $em->flush();
 // Envoi de l'e-mail
 $email = (new Email())
 ->from('bouhjarons27@gmail.com')
 ->to('bouhjarons27@gmail.com')
 ->subject('Nouvelle réclamation')
 ->html('<p>Une nouvelle réclamation a été soumise:</p>' .
 '<ul>' .
 '<li>Type de reclamation: ' . $reclamation->getTypeReclamation() . '</li>' .
 '<li>Sujet: ' . $reclamation->getSujet() . '</li>' .
 '<li>Reclamation: ' . $reclamation->getTextRec() . '</li>' .
 '</ul>');


$mailer->send($email);
            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reclamation/new.html.twig', [
            'title' => 'Ajouter',
            'subtitle' => 'reclamations',
            'controller_name' => 'ReclamationController',

            'form' => $form->createView(),
        ]);
    }

    #[Route('/reclamation/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    #[Route('/reclamation/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/reclamation/{id}', name: 'app_reclamation_delete')]
    public function delete(Reclamation $reclamation): RedirectResponse
    {
            $em = $this->getDoctrine()->getManager();
        $em->remove($reclamation);
        $em->flush();
        

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }




  

    #[Route('/reclamation/pdf/{id}', name: 'app_rec_pdf')]
    public function PDFreponse($id, ReclamationRepository $repo)
    {
        $reclamation = $repo->find($id);
        $reclamations = [$reclamation];
    
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
    
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
    
        // Retrieve the HTML generated in our twig file
        $dompdf->loadHtml($this->renderView('reclamation/pdf.html.twig', [
            'reclamation' => $reclamations
        ]));
    
        // Load HTML to Dompdf
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
    
        // Set the response content
        $response = new Response();
        $response->headers->set('Content-Type', 'application/pdf');
        $response->setContent($dompdf->output());
    
        // Return the response
        return $response;
    }
    


    
    #[Route('/pdffff', name: 'pdf_all_recs')]
    public function pdfAllReponses(ReclamationRepository $repo): Response
    {
        // Récupérer toutes les reclamations depuis la base de données
        $reclamations = $repo->findAll();
    
        // Configurer Dompdf selon vos besoins
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
    
        $dompdf = new Dompdf($pdfOptions);
    
        // Charger le contenu HTML des reclamations dans Dompdf
        $dompdf->loadHtml($this->renderView('reclamation/pdf.html.twig', ['reclamation' => $reclamations]));
    
        // Définir le format de la page
        $dompdf->setPaper('A4', 'portrait');
    
        // Générer le PDF
        $dompdf->render();
    
        // Renvoyer la reclamation avec le contenu PDF en pièce jointe
        $response = new Response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="Toutes_les_reclamations.pdf"',
        ]);
    
        return $response;
    }
    

}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reclamation{% endblock %}


{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
<br/><br/><br/><br/><br/>

{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation {% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

   
{# Search form #}
	<form method="get" action="{{ path('app_reclamation_index') }}" class="mb-4">
		<div class="input-group">
			<input type="text" name="q" value="{{ app.request.get('q') }}" class="form-control" placeholder="Rechercher une Reclamation">
			<button type="submit" class="btn btn-primary">Rechercher</button>
		</div>
	</form>

	{# Search results #}
	{% if reclamation is not empty %}
		<table class="table">
			<thead>
				<tr>
					
                    <th scope="col">Text_rec</th>
                    <th scope="col">Sujet</th>
                    <th scope="col">type reclamation</th>
                    <th scope="col">Id_user</th>
				</tr>
			</thead>
			<tbody>
				
				{% for reclamation in reclamation %}
					<tr>
					
                        <td>{{ reclamation.textRec }}</td>
                        <td>{{ reclamation.sujet }}</td>
                        <td>{{ reclamation.typeReclamation }}</td>
                        <td>{{ reclamation.idUser }}</td>
						<td>
							 <div class="d-flex justify-content-between align-items-center">
								<div class="btn-group">
									<a href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">
										<button type="submit" class="btn btn-primary">Modifier</button>
									</a>
									<a href="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onclick="return confirm('Êtes-vous sûr de bien vouloir supprimer cette Reclamation?')">
										<button type="submit" class="btn btn-primary" style="margin-left: 10px;">Supprimer</button>
									</a>

									<a href="{{ path('app_rec_pdf',{'id':reclamation.id}) }}">Telecharger PDF</a>
								</div>
							</div>

						</td>
					</tr>
				{% endfor %}
			</tbody>
					   <a href="{{ path('pdf_all_recs') }}" class="btn btn-primary view-inv-btn">Telecharger la liste des reclamations</a>

		</table>

	{% else %}
		<p>Aucun reclamation ne correspond à votre recherche.</p>
	{% endif %}

    <br/><br/><br/><br/><br/>
 {% include "chat/index.html.twig" %}

{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reclamation{% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Create new Reclamation</h1>

    {{ include('reclamation/_form.html.twig') }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>
    <br/><br/><br/><br/><br/>

{% endblock %}

templates/reclamation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Text_rec</th>
                <td>{{ reclamation.textRec }}</td>
            </tr>
            <tr>
                <th>Sujet</th>
                <td>{{ reclamation.sujet }}</td>
            </tr>
         
            <tr>
                <th>Id_user</th>
                <td>{{ reclamation.idUser }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
    <br/><br/><br/><br/><br/>

{% endblock %}