src/Entity/Moyentransport.php
<?php

namespace App\Entity;

use App\Repository\MoyentransportRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormTypeInterface;


#[ORM\Entity(repositoryClass: MoyentransportRepository::class)]
class Moyentransport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_moy = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $matricule = null;

    public function getId_moy(): ?int
    {
        return $this->id_moy;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }
}

src/Form/MoyentransportType.php
<?php

namespace App\Form;

use App\Entity\Moyentransport;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormTypeInterface;

class MoyentransportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type')
            ->add('nb_place')
            ->add('marque')
            ->add('matricule')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Moyentransport::class,
        ]);
    }
}

src/Controller/MoyentransportController.php
<?php

namespace App\Controller;

use App\Entity\Moyentransport;
use App\Form\MoyentransportType;
use App\Repository\MoyentransportRepository;
use Exception;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\MoyentrasportType;
use Symfony\Component\Form\FormTypeInterface;


class MoyentransportController extends AbstractController
{
    #[Route('/moyentransport', name: 'app_moyentransport')]
    public function index(Request $request, MoyentransportRepository $moyentransportRepository): Response
    {   $orderBy = $request->query->get('orderBy', 'id_moy'); // default to sorting by id_moy
        $direction = $request->query->get('direction', 'desc'); // default to descending order
    
        if ($direction !== 'asc' && $direction !== 'desc') {
            $direction = 'asc';
        }
        $moyentransports = $moyentransportRepository->findBy([], [$orderBy => $direction]);
    
    
        return $this->render('moyentransport/index.html.twig', [
            'moyentransports' => $moyentransports,
            'orderBy' => $orderBy,
            'direction' => $direction,
        ]);
    }
    #[Route('/moyentransport/new', name: 'app_add_moyentransport')]
    public function add(Request $request): Response
    {
        $moyentransport = new Moyentransport();
        $form = $this->createForm(MoyentransportType::class, $moyentransport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($moyentransport);
            $em->flush();
            return $this->redirectToRoute('app_moyentransport', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('moyentransport/add.html.twig', [
            'moyentransport' => $moyentransport,
            'form' => $form,
        ]);
    }
    #[Route('/moyentransport/{id}/delete', name: 'app_delete_moyentransport')]
    public function delete(Moyentransport $moyentransport): RedirectResponse
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($moyentransport);
        $em->flush();

        return $this->redirectToRoute('app_moyentransport'); //specific the name of the route
    }

     #[Route('/moyentransport/{id}', name: 'app_moyentransport_show', methods: ['GET'])]
     public function show(Moyentransport $moyentransport): Response
     {
         return $this->render('moyentransport/index.html.twig', [
             'moyentransport' => $moyentransport,
         ]);
     }
   
    #[Route('/moyentransport/{id}/edit', name: 'app_moyentransport_edit')]
   public function edit(Request $request, Moyentransport $moyentransport): Response
    {
        $form = $this->createForm(MoyentransportType::class, $moyentransport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('app_moyentransport', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('moyentransport/edit.html.twig', [
            'moyentransport' => $moyentransport,
            'form' => $form,
        ]);
    }
}

templates/moyentransport/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Moyentransport{% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Publier Moyentransport</h1>

    {{form_start(form)}}

    {{include('layouts/_moyentransportForm.html.twig')}}

    <button class="btn btn-outline-primary">Ajouter moyentransport</button>

    {{form_end(form)}}
    <br/><br/><br/><br/><br/>

{% endblock %}

templates/moyentransport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}EditMoyentansportController{% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Editer Moyentansport</h1>

    {{form_start(form)}}

    {{include('layouts/_moyentransportForm.html.twig')}}

    <button class="btn btn-outline-primary">Editer moyentansport</button>

    {{form_end(form)}}
    <br/><br/><br/><br/><br/>

{% endblock %}

templates/moyentransport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Moyentransport index{% endblock %}

{% block body %}
<br/><br/><br/><br/><br/>

    <h1>Moyentransport index</h1>
    {% for key, messages in app.session.flashbag.all() %}
        {% for message in messages %}
            <div class="alert alert-{{ key }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
    <table class="table">
        <thead>
            <tr>
               
                 {# <th><a href="{{ path('app_moyentransport_index') }}?orderBy=id_moy&direction={{ direction == 'asc' and orderBy == 'id_moy' ? 'desc' : 'asc' }}">Id_moy</a></th> #}
<th><a href="{{ path('app_moyentransport') }}?orderBy=type&direction={{ direction == 'asc' and orderBy == 'type' ? 'desc' : 'asc' }}">Type</a></th>
<th><a href="{{ path('app_moyentransport') }}?orderBy=nb_place&direction={{ direction == 'asc' and orderBy == 'nb_place' ? 'desc' : 'asc' }}">Nb_place</a></th>
<th><a href="{{ path('app_moyentransport') }}?orderBy=marque&direction={{ direction == 'asc' and orderBy == 'marque' ? 'desc' : 'asc' }}">Marque</a></th>
<th><a href="{{ path('app_moyentransport') }}?orderBy=matricule&direction={{ direction == 'asc' and orderBy == 'matricule' ? 'desc' : 'asc' }}">Matricule</a></th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for moyentransport in moyentransports %}
            <tr>
                 <td>{{ moyentransport.id_moy }}</td> 
                <td>{{ moyentransport.type }}</td>
                <td>{{ moyentransport.nbPlace }}</td>
                <td>{{ moyentransport.marque }}</td>
                <td>{{ moyentransport.matricule }}</td>
                <td>
                    <a href="{{ path('app_moyentransport_edit', {'id': moyentransport.id_moy}) }}">edit</a>
                    <a href="{{ path('app_delete_moyentransport', {'id': moyentransport.id_moy}) }}">DELETE</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_add_moyentransport') }}">Create new</a>
    <br/><br/><br/><br/><br/>

{% endblock %}